# Generated by Django 5.0.1 on 2025-08-31 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('exam_limit', models.PositiveIntegerField(help_text='Number of exams allowed')),
                ('duration_days', models.PositiveIntegerField(help_text='Plan duration in days')),
                ('allows_scheduled_exams', models.BooleanField(default=True)),
                ('allows_unlimited_retakes', models.BooleanField(default=True)),
                ('includes_analytics', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'price'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='subscriptio_is_acti_07abd2_idx'), models.Index(fields=['price'], name='subscriptio_price_704aa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('exams_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(default='sslcommerz', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('renewal_reminder_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exam_taken_at', models.DateTimeField(auto_now_add=True)),
                ('score_achieved', models.FloatField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscription_usage',
                'ordering': ['-exam_taken_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100)),
                ('transaction_type', models.CharField(choices=[('subscription', 'Subscription Payment'), ('renewal', 'Subscription Renewal'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('payment_gateway', models.CharField(choices=[('sslcommerz', 'SSLCommerz'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], default='sslcommerz', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payment_tra_transac_4a22d3_idx'), models.Index(fields=['gateway_transaction_id'], name='payment_tra_gateway_532615_idx'), models.Index(fields=['user', 'status'], name='payment_tra_user_id_131e27_idx'), models.Index(fields=['status', 'created_at'], name='payment_tra_status_ea288f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_b63ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='subscriptio_end_dat_763002_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['payment_status'], name='subscriptio_payment_1c2550_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['transaction_id'], name='subscriptio_transac_98f8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusage',
            index=models.Index(fields=['subscription', 'exam_taken_at'], name='subscriptio_subscri_113d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusage',
            index=models.Index(fields=['exam', 'exam_taken_at'], name='subscriptio_exam_id_21bcf8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionusage',
            unique_together={('subscription', 'exam', 'exam_taken_at')},
        ),
    ]
