# Generated by Django 5.0.1 on 2025-08-31 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects/')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='subjects_is_acti_754344_idx'), models.Index(fields=['code'], name='subjects_code_3f80fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('chapter_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Chapter content/description')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='subjects.subject')),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['subject', 'chapter_number'],
                'indexes': [models.Index(fields=['subject', 'is_active'], name='chapters_subject_9a0fc7_idx'), models.Index(fields=['chapter_number'], name='chapters_chapter_19736b_idx'), models.Index(fields=['difficulty_level'], name='chapters_difficu_0ee470_idx')],
                'unique_together': {('subject', 'chapter_number')},
            },
        ),
    ]
