# Generated by Django 5.0.1 on 2025-08-31 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('subject', 'Subject-wise'), ('chapter', 'Chapter-wise'), ('exam', 'Exam-specific')], max_length=20)),
                ('period', models.CharField(choices=[('all_time', 'All Time'), ('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('max_entries', models.PositiveIntegerField(default=100)),
                ('score_calculation_method', models.CharField(choices=[('average', 'Average Score'), ('best', 'Best Score'), ('total', 'Total Points'), ('weighted', 'Weighted Score')], default='average', max_length=20)),
                ('min_exams_required', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'leaderboard_types',
                'indexes': [models.Index(fields=['scope', 'period'], name='leaderboard_scope_8cf964_idx'), models.Index(fields=['is_active', 'is_public'], name='leaderboard_is_acti_0b1e20_idx')],
                'unique_together': {('scope', 'period', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('leaderboard_data', models.JSONField(default=list)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.chapter')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('leaderboard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='leaderboards.leaderboardtype')),
            ],
            options={
                'db_table': 'leaderboards',
                'ordering': ['-period_end', '-total_participants'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField()),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(default=0)),
                ('score', models.FloatField()),
                ('total_exams', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_score', models.FloatField(default=0.0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('improvement_rate', models.FloatField(default=0.0)),
                ('performance_trend', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable'), ('new', 'New User')], default='new', max_length=20)),
                ('achievements', models.JSONField(default=list)),
                ('badges', models.JSONField(default=list)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leaderboards.leaderboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['leaderboard', 'rank'], name='leaderboard_leaderb_bb9735_idx'), models.Index(fields=['user', 'rank'], name='leaderboard_user_id_517e2c_idx'), models.Index(fields=['score'], name='leaderboard_score_631d31_idx')],
                'unique_together': {('leaderboard', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notify_on_rank_change', models.BooleanField(default=True)),
                ('notify_on_new_achievements', models.BooleanField(default=True)),
                ('notify_on_period_end', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.chapter')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('leaderboard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.leaderboardtype')),
            ],
            options={
                'db_table': 'leaderboard_subscriptions',
                'unique_together': {('user', 'leaderboard_type', 'subject', 'chapter')},
            },
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['leaderboard_type', 'period_start', 'period_end'], name='leaderboard_leaderb_b10a56_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['subject', 'period_start'], name='leaderboard_subject_5f956f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['chapter', 'period_start'], name='leaderboard_chapter_4c4869_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['exam'], name='leaderboard_exam_id_74f9dd_idx'),
        ),
    ]
