# Generated by Django 5.0.1 on 2025-09-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_question_selection_method_and_more'),
        ('leaderboards', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaderboardtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaderboardtype',
            name='exam_type_filter',
            field=models.CharField(choices=[('all', 'All Types'), ('scheduled', 'Scheduled Only'), ('practice', 'Practice Only'), ('self_paced', 'Self Paced Only')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='leaderboardtype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaderboardtype',
            name='period',
            field=models.CharField(choices=[('all_time', 'All Time'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaderboardtype',
            name='score_calculation_method',
            field=models.CharField(choices=[('average', 'Average Score'), ('best', 'Best Score'), ('total', 'Total Points'), ('weighted', 'Weighted Score')], default='best', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardtype',
            unique_together={('scope', 'period', 'name', 'exam_type_filter')},
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['is_finalized'], name='leaderboard_is_fina_f90340_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardtype',
            index=models.Index(fields=['is_default', 'exam_type_filter'], name='leaderboard_is_defa_c61c4d_idx'),
        ),
    ]
