# Generated by Django 5.0.1 on 2025-09-01 17:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('self_paced', 'Self Paced'), ('scheduled', 'Scheduled'), ('practice', 'Practice')], default='self_paced', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=50)),
                ('questions_per_chapter', models.JSONField(blank=True, default=dict)),
                ('difficulty_distribution', models.JSONField(blank=True, default=dict)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_options', models.BooleanField(default=True)),
                ('duration_minutes', models.PositiveIntegerField(default=50)),
                ('time_per_question', models.FloatField(default=1.0)),
                ('allow_custom_duration', models.BooleanField(default=True)),
                ('max_duration_minutes', models.PositiveIntegerField(default=180)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('marks_per_question', models.FloatField(default=1.0)),
                ('negative_marking_enabled', models.BooleanField(default=True)),
                ('negative_marks', models.FloatField(default=0.25)),
                ('passing_percentage', models.FloatField(default=60.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('requires_subscription', models.BooleanField(default=True)),
                ('allow_retakes', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=0)),
                ('auto_submit_on_time_up', models.BooleanField(default=True)),
                ('grace_period_seconds', models.PositiveIntegerField(default=30)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('chapters', models.ManyToManyField(related_name='exams', to='subjects.chapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_questions', models.JSONField(default=list)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('auto_submitted', 'Auto Submitted'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('answers_submitted', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('tab_switches', models.PositiveIntegerField(default=0)),
                ('suspicious_activity', models.JSONField(default=list)),
                ('total_score', models.FloatField(default=0.0)),
                ('percentage_score', models.FloatField(default=0.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question_number', models.PositiveIntegerField()),
                ('options_order', models.JSONField(default=list)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('visited_count', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.examsession')),
            ],
            options={
                'db_table': 'exam_questions',
                'ordering': ['session', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.FloatField(default=0.0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('answer_sequence', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession')),
            ],
            options={
                'db_table': 'exam_answers',
                'ordering': ['session', 'question'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'is_active'], name='exams_exam_ty_94488f_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['scheduled_start', 'scheduled_end'], name='exams_schedul_6c3d15_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by'], name='exams_created_7a6aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_public', 'is_active'], name='exams_is_publ_181ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'status'], name='exam_sessio_user_id_ba53c6_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'status'], name='exam_sessio_exam_id_7e2d43_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['started_at', 'ended_at'], name='exam_sessio_started_7e85d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('exam', 'user', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['session', 'question_number'], name='exam_questi_session_1d32b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('session', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['session', 'question'], name='exam_answer_session_c8af35_idx'),
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['is_correct'], name='exam_answer_is_corr_4124a8_idx'),
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['answered_at'], name='exam_answer_answere_6e56ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('session', 'question')},
        ),
    ]
