# Generated by Django 5.0.1 on 2025-09-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_selection_method',
            field=models.CharField(choices=[('random', 'Random Selection'), ('manual', 'Manual Selection'), ('mixed', 'Mixed (Random + Manual)')], default='random', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='random_questions_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of random questions when using mixed selection'),
        ),
        migrations.AddField(
            model_name='exam',
            name='selected_questions',
            field=models.JSONField(blank=True, default=list, help_text='List of manually selected question IDs'),
        ),
    ]
