# Generated by Django 5.0.1 on 2025-10-03 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_question_selection_method_and_more'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('difficulty_distribution', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('chapters', models.ManyToManyField(related_name='question_sets', to='subjects.chapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_question_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_sets',
                'ordering': ['-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['created_by', 'is_active'], name='question_se_created_bce870_idx'), models.Index(fields=['usage_count'], name='question_se_usage_c_d831ae_idx'), models.Index(fields=['-created_at'], name='question_se_created_aabdce_idx')],
            },
        ),
    ]
