# Generated by Django 5.0.1 on 2025-09-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
    ]
